<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'October\\Demo\\Components\\Todo' => 'plugins\\october\\demo\\components\\Todo.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'system\\Controllers\\eventlogs' => 'modules\\system\\controllers\\eventlogs.php',
  'backend\\Controllers\\users' => 'modules\\backend\\controllers\\users.php',
  'admin\\test\\Plugin' => 'plugins\\admin\\test\\Plugin.php',
  'admin\\test\\Controllers\\contacts' => 'plugins\\admin\\test\\controllers\\contacts.php',
  'Admin\\Test\\Models\\Contact' => 'plugins\\admin\\test\\models\\Contact.php',
  'admin\\test\\Controllers\\cities' => 'plugins\\admin\\test\\controllers\\cities.php',
  'Admin\\Test\\Models\\City' => 'plugins\\admin\\test\\models\\City.php',
  'Admin\\Test\\Components\\Contact' => 'plugins\\admin\\test\\components\\Contact.php',
  'Admin\\Test\\Components\\Feedback' => 'plugins\\admin\\test\\components\\Feedback.php',
  'admin\\test\\Controllers\\feedback' => 'plugins\\admin\\test\\controllers\\feedback.php',
  'Admin\\Test\\Models\\Feedback' => 'plugins\\admin\\test\\models\\Feedback.php',
  'system\\Controllers\\mailtemplates' => 'modules\\system\\controllers\\mailtemplates.php',
  'backend\\Controllers\\accesslogs' => 'modules\\backend\\controllers\\accesslogs.php',
);